name: rucio-daemons
version: 0.8.0
apiVersion: v1
description: A Helm chart to deploy daemons for Rucio
keywords:
  - data-management
  - science
home: https://rucio.cern.ch/
sources:
  - https://github.com/rucio/rucio
maintainers:
  - name: Thomas Beermann
    email: thomas.beermann@cern.ch

