apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-probes.config.yaml
  labels:
    app: {{ template "rucio-probes.name" . }}
    chart: {{ template "rucio-probes.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  common.json: {{ $common_config | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-probes
  labels:
    app: {{ template "rucio-probes.name" . }}
    chart: {{ template "rucio-probes.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ template "rucio-probes.name" . }}
      release: {{ .Release.Name }}

  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "rucio-probes.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ $common_config | sha1sum }}
    spec:
      volumes:
        - name: config
          secret:
            secretName: {{ .Release.Name }}-probes.config.yaml
        - configMap:
            defaultMode: 0644
            name: {{ include "rucio-probes.fullname" . }}-jobber-config
          name: jobber-config
{{- if hasKey .Values.probeSettings "ftsProxySecret" }}
        - name: proxy-volume
          secret:
            defaultMode: 420
            secretName: "{{ .Values.probeSettings.ftsProxySecret }}"
{{- end }}

      containers:
      - env:
        - name: RUCIO_OVERRIDE_CONFIGS
          value: "/opt/rucio/etc/conf.d/"
        image: "{{ include "rucio.image.registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        volumeMounts:
        - name: config
          mountPath: /opt/rucio/etc/conf.d/10_common.json
          subPath: common.json
        - mountPath: /etc/jobber-config/
          name: jobber-config
{{- if hasKey .Values.probeSettings "ftsProxySecret" }}
        - mountPath: /opt/proxy
          name: proxy-volume
{{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
{{- end}}
{{- with .Values.resources }}
        resources:
{{ toYaml . | trim | indent 12 }}
{{ end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
