apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rucio.fullname" . }}-aliases
  labels:
    app: {{ template "rucio.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  aliases.conf: |+
    Alias /media        /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/media
    Alias /static       /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/static
    WSGIScriptAlias /   /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/main.py
