{{- if gt .Values.replicaCount 0.0 -}}
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rucio.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressApiVersion := include "rucio.kubeApiVersion.ingress" . -}}
apiVersion: {{ $ingressApiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
{{ end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
    {{- if eq $ingressApiVersion "networking.k8s.io/v1" }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.Values.service.port }}
            pathType: Prefix
    {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.Values.service.port }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
