{{- if gt .Values.automatixCount 0.0 -}}
{{- $rucio_daemon := "automatix" }}
{{- $component_values := .Values.automatix }}
{{- $component_count := .Values.automatixCount }}
{{- $app_label := printf "%s-%s" (include "rucio.name" .) $rucio_daemon }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.{{ $rucio_daemon }}
  labels:
    app: {{ $app_label }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  {{- $component_config := $component_values.config | default dict | mustToPrettyJson | b64enc }}
  component.json: {{ $component_config | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ $rucio_daemon }}
  labels:
    app: {{ $app_label }}
    app-group: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ $component_count }}
  selector:
    matchLabels:
      app: {{ $app_label }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ $app_label }}
        app-group: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
        rucio-daemon: {{ $rucio_daemon }}
    {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      annotations:
        checksum/config: {{ print "%s%s" $common_config $component_config | sha1sum }}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $component_values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: config-common
        secret:
          secretName: {{ template "rucio.fullname" . }}.config.common
      - name: config-component
        secret:
          secretName: {{ template "rucio.fullname" . }}.config.{{ $rucio_daemon }}
    {{- if .Values.useDeprecatedImplicitSecrets }}
      - name: proxy-volume
        secret:
          secretName: {{ .Release.Name }}-rucio-x509up
      - name: ca-volume
        secret:
          secretName: {{ .Release.Name }}-rucio-ca-bundle
      - name: ca-volume-reaper
        secret:
          secretName: {{ .Release.Name }}-rucio-ca-bundle-reaper
    {{- end }}
      {{- range $collection := tuple (coalesce $component_values.secretMounts .Values.secretMounts) $component_values.extraSecretMounts }}
      {{- range $key, $val := $collection }}
      - name: {{ coalesce $val.volumeName $val.secretName $val.secretFullName }}
        secret:
          secretName: {{ coalesce $val.secretFullName (printf "%s-%s" $.Release.Name $val.secretName) }}
          {{- if $val.defaultMode }}
          defaultMode: {{ $val.defaultMode }}
          {{- end }}
      {{- end}}
      {{- end}}
      {{- range $key, $val := .Values.persistentVolumes }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $val.name }}
      {{- end}}
      {{- range $collection := tuple (hasKey $component_values "hostPathMounts" | ternary $component_values.hostPathMounts .Values.hostPathMounts) $component_values.extraHostPathMounts }}
      {{- range $key, $val := $collection }}
      - name: {{ $val.volumeName | default (printf "a%s" ($val.mountPath | sha1sum)) }}
        hostPath:
        {{- if $val.type }}
          type: {{ $val.type }}
        {{- end}}
          path: {{ $val.hostPath }}
      {{- end}}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ coalesce ($component_values.image | default dict).tag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- if .Values.useDeprecatedImplicitSecrets }}
            - name: proxy-volume
              mountPath: /opt/proxy
            - name: ca-volume
              mountPath: /opt/certs
            - name: ca-volume-reaper
              mountPath: /etc/grid-security/certificates
          {{- end }}
            - name: config-common
              mountPath: /opt/rucio/etc/conf.d/10_common.json
              subPath: common.json
            - name: config-component
              mountPath: /opt/rucio/etc/conf.d/20_component.json
              subPath: component.json
            {{- range $collection := tuple (coalesce $component_values.secretMounts .Values.secretMounts) $component_values.extraSecretMounts }}
            {{- range $key, $val := $collection }}
            - name: {{ coalesce $val.volumeName $val.secretName $val.secretFullName }}
              mountPath: {{ $val.mountPath }}
              {{- if $val.subPath }}
              subPath: "{{ $val.subPath }}"
              {{- end }}
            {{- end}}
            {{- end}}
            {{- range $key, $val := .Values.persistentVolumes }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
            {{- end}}
          {{- range $collection := tuple (hasKey $component_values "hostPathMounts" | ternary $component_values.hostPathMounts .Values.hostPathMounts) $component_values.extraHostPathMounts }}
          {{- range $key, $val := $collection }}
            - name: {{ $val.volumeName | default (printf "a%s" ($val.mountPath | sha1sum)) }}
              mountPath: {{ $val.mountPath }}
              readOnly: {{ $val.readOnly | default false }}
          {{- end}}
          {{- end}}
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          env:
            {{- range $key1, $val1 := .Values.optional_config }}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
            {{- end}}
            - name: RUCIO_OVERRIDE_CONFIGS
              value: "/opt/rucio/etc/conf.d/"
            - name: RUCIO_DAEMON
              value: "{{ $rucio_daemon }}"
            - name: RUCIO_DAEMON_ARGS
              value: "{{- if $component_values.threads }} --threads-per-process {{ $component_values.threads }}{{ end }} {{- if $component_values.inputFile }} --input-file {{ $component_values.inputFile }}{{ end }} {{- if $component_values.sleepTime }} --sleep-time {{ $component_values.sleepTime }}{{ end }}"
            {{- if .Values.useDeprecatedImplicitSecrets }}
            - name: X509_USER_PROXY
              value: "/opt/proxy/x509up"
            {{- end }}
{{- with $component_values.additionalEnvs }}
{{ toYaml . | indent 12 }}
{{- end}}
{{- with $component_values.resources }}
          resources:
{{ toYaml . | trim | indent 12 }}
{{ end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
{{- end}}
{{- with $component_values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $component_values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with $component_values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{ end }}
