apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.common
  labels:
    app: {{ template "rucio.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  common.json: {{ $common_config | quote }}
