{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app-group: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.monitoring.exporterPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app-group: {{ template "rucio.name" . }}
    release: {{ .Release.Name }}
{{ end }}
