apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.common
  labels:
    app: {{ template "rucio.name" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  common.json: {{ $common_config | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.cfg
  labels:
    app: {{ template "rucio.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- range $key, $val := .Values.httpd_config }}
  {{ $key }}: {{ $val | b64enc | quote}}
  {{- end}}
