{{- if gt .Values.traceReplicaCount 0.0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.fullname" . }}-trace
  labels:
    app: {{ template "rucio.name" . }}-trace
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.traceService.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.traceService.type }}
  ports:
    - port: {{ .Values.traceService.port }}
      targetPort: {{ .Values.traceService.targetPort }}
      protocol: {{ .Values.traceService.protocol }}
      name: {{ .Values.traceService.name }}
  selector:
    app: {{ template "rucio.name" . }}-trace
    release: {{ .Release.Name }}
{{- if .Values.traceService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.traceService.loadBalancerIP }}
{{- end }}
{{- if .Values.traceService.loadBalancerClass }}
  loadBalancerClass: {{ .Values.traceService.loadBalancerClass }}
{{- end }}
{{- if not .Values.traceService.allocateLoadBalancerNodePorts }}
  allocateLoadBalancerNodePorts: {{ .Values.traceService.allocateLoadBalancerNodePorts }}
{{- end }}
{{- end }}