apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rucio.fullname" . }}.config.yaml
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- $common_config := .Values.config | default dict | mustToPrettyJson | b64enc }}
  common.json: {{ $common_config | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy.type }}
{{- if eq .Values.strategy.type "RollingUpdate" }}
    {{- with .Values.strategy.rollingUpdate }}
    rollingUpdate:
{{ toYaml . | trim | indent 6 }}
    {{- end }}
{{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  template:
    metadata:
      labels:
        app: {{ template "rucio.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ $common_config | sha1sum }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
      volumes:
      - name: config
        secret:
          secretName: {{ template "rucio.fullname" . }}.config.yaml
      - name: httpdlog
        emptyDir: {}
      - name: webui-log
        emptyDir: {}
      {{- if .Values.useDeprecatedImplicitSecrets }}
      {{- if eq .Values.useSSL true }}
      - name: hostcert
        secret:
          secretName: {{ .Release.Name }}-hostcert
      - name: hostkey
        secret:
          secretName: {{ .Release.Name }}-hostkey
      - name: cafile
        secret:
          secretName: {{ .Release.Name }}-cafile
      {{- end }}
      {{- end }}
      {{- range $key, $val := .Values.secretMounts }}
      - name: {{ coalesce $val.volumeName $val.secretName $val.secretFullName }}
        secret:
          secretName: {{ coalesce $val.secretFullName (printf "%s-%s" $.Release.Name $val.secretName) }}
      {{- end}}
      {{- range $key, $val := .Values.persistentVolumes }}
      - name: {{ $key }}
        persistentVolumeClaim:
          claimName: {{ $val.name }}
      {{- end}}
      {{- range $collection := tuple .Values.hostPathMounts }}
      {{- range $key, $val := $collection }}
      - name: {{ $val.volumeName | default (printf "a%s" ($val.mountPath | sha1sum)) }}
        hostPath:
          {{- if $val.type }}
          type: {{ $val.type }}
          {{- end}}
          path: {{ $val.hostPath }}
      {{- end}}
      {{- end}}
      containers:
      {{- if .Values.config.logs.exposeHttpdLogs }}
        - name: httpd-error-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/httpd/error_log']
          volumeMounts:
          - name: httpdlog
            mountPath: /var/log/httpd
      {{- end }}
      {{- if .Values.config.logs.exposeWebuiLogs }}
        - name: webui-log
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/webui/rucio-webui-out.log /var/log/webui/rucio-webui-error.log']
          volumeMounts:
          - name: webui-log
            mountPath: /var/log/webui/
      {{- end }}
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.useSSL }}
            - name: https
              containerPort: 443
              protocol: TCP
            {{- end }}
          volumeMounts:
            {{- if .Values.config.logs.exposeHttpdLogs }}
            - name: httpdlog
              mountPath: /var/log/httpd
            {{- end }}
            {{- if .Values.config.logs.exposeWebuiLogs }}
            - name: webui-log
              mountPath: /root/.pm2/logs/
            {{- end }}
            {{- if .Values.useDeprecatedImplicitSecrets }}
            {{- if .Values.useSSL }}
            - name: hostcert
              mountPath: /etc/grid-security/hostcert.pem
              subPath: hostcert.pem
            - name: hostkey
              mountPath: /etc/grid-security/hostkey.pem
              subPath: hostkey.pem
            - name: cafile
              mountPath: /etc/grid-security/ca.pem
              subPath: ca.pem
            {{- end}}
            {{- end}}
            {{- range $key, $val := .Values.secretMounts }}
            - name: {{ coalesce $val.volumeName $val.secretName $val.secretFullName }}
              mountPath: {{ $val.mountPath }}
              subPath: {{ $val.subPath }}
            {{- end}}
            {{- range $collection := tuple .Values.hostPathMounts }}
            {{- range $key, $val := $collection }}
            - name: {{ $val.volumeName | default (printf "a%s" ($val.mountPath | sha1sum)) }}
              mountPath: {{ $val.mountPath }}
              readOnly: {{ $val.readOnly | default false }}
            {{- end}}
            {{- end}}
            {{- range $key, $val := .Values.persistentVolumes }}
            - name: {{ $key }}
              mountPath: {{ $val.mountPath }}
            {{- end}}
          env:
            {{- range $key, $val := .Values.config.httpd }}
            - name: RUCIO_HTTPD_{{ $key | snakecase | upper }}
              value: {{ $val | quote }}
            {{- end }}
            {{- range $key, $val := .Values.config.webui }}
            - name: RUCIO_WEBUI_{{ $key | snakecase | upper }}
              value: {{ $val | quote }}
            {{- end }}
            {{ range $provider, $data := .Values.config.oidc_providers }}
            {{- range $key, $val := $data }}
            - name: RUCIO_WEBUI_OIDC_PROVIDER_{{ $provider | snakecase | upper }}_{{ $key | snakecase | upper}}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{ range $vo, $data := .Values.config.vo }}
            {{- range $key, $val := $data }}
            - name: RUCIO_WEBUI_VO_{{ $vo | snakecase | upper }}_{{ $key | snakecase | upper}}
              value: {{ $val | quote }}
            {{- end }}
            {{- end }}
            {{- range $key1, $val1 := .Values.optionalConfig }}
            - name: {{ $key1 | upper }}
              value: "{{ $val1  }}"
            {{- end}}
            - name: RUCIO_LOG_LEVEL
              value: "INFO"
            - name: RUCIO_ENABLE_LOGS
              value: "True"
            - name: RUCIO_LOG_FORMAT
              value: '[%{%Y-%m-%d %H:%M:%S}t]\t%v\t%h\t%{X-Forwarded-For}i\t%{X-Rucio-RequestId}i\t%>s\t%I\t%B\t%D\t\"%r\"\t\"%{X-Rucio-Auth-Token}i\"\t\"%{User-Agent}i\"\t%{X-Rucio-Script}i'
          {{- if not .Values.useSSL }}
            - name: RUCIO_WEBUI_ENABLE_SSL
              value: "False"
          {{- else }}
            - name: RUCIO_WEBUI_ENABLE_SSL
              value: "True"
          {{- end }}
{{- with .Values.additionalEnvs }}
{{ toYaml . | indent 12 }}
{{- end}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
{{- end}}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
