{{- if gt .Values.replicaCount 0.0 -}}
{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitorEnabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if .Values.monitoring.labels }}
  labels:
{{ toYaml .Values.monitoring.labels | indent 4}}
{{- end }}
  name: {{ template "rucio.fullname" . }}
{{- if .Values.monitoring.namespace }}
  namespace: {{ .Values.monitoring.namespace }}
{{- end }}
spec:
  endpoints:
  - targetPort: {{ .Values.monitoring.exporterPort }}
 {{- if .Values.monitoring.interval }}
    interval: {{ .Values.monitoring.interval }}
 {{- end }}
 {{- if .Values.monitoring.telemetryPath }}
    path: {{ .Values.monitoring.telemetryPath }}
 {{- end }}
{{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.monitoring.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.monitoring.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.monitoring.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  - targetPort: {{ .Values.monitoring.nativeMetricsPort }}
 {{- if .Values.monitoring.interval }}
    interval: {{ .Values.monitoring.interval }}
 {{- end }}
    path: /metrics/
{{- if .Values.monitoring.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.monitoring.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.monitoring.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.monitoring.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  jobLabel: {{ template "rucio.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ template "rucio.name" . }}
      release: {{ .Release.Name }}
{{ end }}
{{ end }}