{{- if .Values.ftsRenewal.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-renew-fts-proxy
spec:
  schedule: "12 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-rucio-edit
          volumes:
{{- if or (eq .Values.ftsRenewal.vo "atlas") (eq .Values.ftsRenewal.vo "dteam") }}
          - name: longproxy
            secret:
              secretName: {{ .Release.Name }}-longproxy
{{- else }}
          - name: usercert
            secret:
              secretName: {{ .Release.Name }}-fts-cert
          - name: userkey
            secret:
              secretName: {{ .Release.Name }}-fts-key
{{- end }}
          containers:
            - name: renew-fts-cron
              image: "{{ .Values.ftsRenewal.image.repository }}:{{ .Values.ftsRenewal.image.tag }}"
              imagePullPolicy: {{ .Values.ftsRenewal.image.pullPolicy }}
              volumeMounts:
{{- if or (eq .Values.ftsRenewal.vo "atlas") (eq .Values.ftsRenewal.vo "dteam") }}
                - name: longproxy
                  mountPath: /opt/rucio/certs/
{{- else }}
                - name: usercert
                  mountPath: /opt/rucio/certs/
                - name: userkey
                  mountPath: /opt/rucio/keys/
{{- end }}
              env:
                {{- range $key1, $val1 := .Values.optional_config }}
                - name: {{ $key1 | upper }}
                  value: "{{ $val1  }}"
                {{- end}}

                - name: RUCIO_VO
                  value: {{ .Values.ftsRenewal.vo | quote }}
                - name: RUCIO_FTS_VOMS
                  value: {{ .Values.ftsRenewal.voms | quote }}
                - name: RUCIO_FTS_SERVERS
                  value: {{ .Values.ftsRenewal.servers | quote }}
                - name: RUCIO_FTS_SECRETS
                  value: "{{ .Release.Name }}-rucio-x509up"
{{- if or (eq .Values.ftsRenewal.vo "atlas") (eq .Values.ftsRenewal.vo "dteam") }}
                - name: RUCIO_LONG_PROXY
                  value: {{ .Values.ftsRenewal.longProxy | quote }}
{{- end }}
          restartPolicy: OnFailure
{{ end }}
